### ISSUE TITLE
External Index for the Data

### ISSUE THREAD

**Issue by satish860** [AnswerDotAI/byaldi#11]
First off, great library! I was aware of Copali but hadn't had a chance to try it until now. This library made it easy to experiment, and the results have been impressive. Now, I'm looking to productionize the process, particularly by separating the indexing process from the search function to improve scalability. From what I understand, the index is stored in memory. If I can locate where it’s stored, I could move it to external storage and load it during search operations.

**Comment by bclavie** [comment]
> First off, great library! I was aware of Copali but hadn't had a chance to try it until now. This library made it easy to experiment, and the results have been impressive. Now, I'm looking to productionize the process, particularly by separating the indexing process from the search function to improve scalability. From what I understand, the index is stored in memory. If I can locate where it’s stored, I could move it to external storage and load it during search operations.

Hey. I'll try to make it clearer, especially as I set out to write some documentation soon, but the index is persisted-on-creation, it never really just lives in memory! This is the purpose of `index_root` and `index_name` in the README. By default, index_root is `./.byaldi`, and `index_name` is the same you pass. Your index will live at `{index_root}/{index_name}`, and you can load it into the library with simple calls:

```python3
RAG = RAGMultiModalModel.from_index(INDEX_NAME, index_root=INDEX_ROOT)
```
