### ISSUE TITLE
Unable to Load vidore/colpali

### ISSUE THREAD

**Issue by zyrdegit** [AnswerDotAI/byaldi#16]
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like vidore/colpaligemma-3b-mix-448-base is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

I downloaded all the files from the "files" section of the vidore/colpali page and saved them in a local folder. I also changed the line model = RAGMultiModalModel.from_pretrained("vidore/colpali") in all.py to use the local address. However, when I run all.py again, it results in an error. I don't know how to resolve this issue and would greatly appreciate any assistance you can provide.

**Comment by tonywu71** [comment]
@ManuelFay I think you encountered something similar recently, am I wrong? I think it had something to do with `peft`!

**Comment by ManuelFay** [comment]
Probably just that you didn't download the base model, just the adapter. 
You could fix this by downloading the vidore/colpaligemma-3b-mix-448-base model as well and changing the path in the adapter-config.json file of your adapter to point to your local base model.

You should probably also use colpali-v1.2.

Agreed it's not optimal ! Could be simpler to use merged versions for local use @tonywu71 ?
