### ISSUE TITLE
I Want to save the Index created by Byaldi - ColPali 

### ISSUE THREAD

**Issue by Manikanta-Qylis** [AnswerDotAI/byaldi#20]
Need help in storing the Index of PDF files to any persistent storage

**Comment by pallabids** [comment]
I need support for the same request

> Need help in storing the Index of PDF files to any persistent storage

**Comment by bclavie** [comment]
Do you want to just save the index? If so, it's saved by default -- there is actually only persistent indexes in byaldi, and all changes are automatically saved to `{index_root}/{index_name}`, where `index_root` by default is `.byaldi` in the folder you're running the script.

I'll add better documentation for this, so I'm keeping the issue open for now. If this isn't what you mean, feel free to clarify 😄

**Comment by pallabids** [comment]
> Do you want to just save the index? If so, it's saved by default -- there is actually only persistent indexes in byaldi, and all changes are automatically saved to `{index_root}/{index_name}`, where `index_root` by default is `.byaldi` in the folder you're running the script.
> 
> I'll add better documentation for this, so I'm keeping the issue open for now. If this isn't what you mean, feel free to clarify 😄

I want to add the indexes in any vector database like elasticsearch or qdrant. is it possible ?

**Comment by bclavie** [comment]
It's possible if your vector DB supports multi-vector representations. Though it's not currently a usecase that we fully support (it'll be added soon), so you'll have to dig in the code to figure out exactly how to extract the embeddings. You can also use the (currently in beta, so undocumented) `encode_image` function at https://github.com/AnswerDotAI/byaldi/blob/b26cf3476876a3e00e12ce565c574489e18448a7/byaldi/colpali.py#L626C9-L626C21 to create and embeddings and add them to your db!

**Comment by wajeeha77** [comment]
hi, I have 27000 images, in the index, and it is taking almost 5-6 mins!! with Vram is 40GBs, to retrieve the results now, (the response time is good for my other document sets with lesser no of pdfs), so how can optimize this to only have 20-40 sec response time.? really need help with this @bclavie

**Comment by bclavie** [comment]
> hi, I have 27000 images, in the index, and it is taking almost 5-6 mins!! with Vram is 40GBs, to retrieve the results now, (the response time is good for my other document sets with lesser no of pdfs), so how can optimize this to only have 20-40 sec response time.? really need help with this @bclavie

@wajeeha77 At this scale, you'd probably want to use some kind of approximate search, or more optimised index. I'd suggest looking into things like Vespa, or using an HNSW index like Voyager to create an index, so you're not scoring _every_ candidate everytime.

**Comment by HafizNouman666** [comment]
> Do you want to just save the index? If so, it's saved by default -- there is actually only persistent indexes in byaldi, and all changes are automatically saved to `{index_root}/{index_name}`, where `index_root` by default is `.byaldi` in the folder you're running the script.
> 
> I'll add better documentation for this, so I'm keeping the issue open for now. If this isn't what you mean, feel free to clarify 😄

hy is their any method available to load embeddings from persistant directory ?
