### ISSUE TITLE
cannot import name 'Unpack' from 'transformers.processing_utils'

### ISSUE THREAD

**Issue by akshaychdr** [AnswerDotAI/byaldi#25]
The code was working fine till this morning but then it started throwing this error while running this line of code:

Code:
RAG = RAGMultiModalModel.from_pretrained("vidore/colpali-v1.2", verbose=1)

Error:
RuntimeError: Failed to import transformers.models.paligemma.processing_paligemma because of the following error (look up to see its traceback):
cannot import name 'Unpack' from 'transformers.processing_utils' (/usr/local/lib/python3.10/dist-packages/transformers/processing_utils.py)

**Comment by bclavie** [comment]
This should be fixed in the most recent release (on pypi in a few minutes), likely due to an old version of transformers -- we now enforce at least 4.42
