### ISSUE TITLE
Enable colqwen?

### ISSUE THREAD

**Issue by mbode** [AnswerDotAI/byaldi#28]
Would it be easily possible to enable using https://huggingface.co/vidore/colqwen2-v0.1 with byaldi?

Currently `RAGMultiModalModel.from_pretrained("vidore/colqwen2-v0.1")` leads to
> ValueError('This pre-release version of Byaldi only supports ColPali for now. Incorrect model name specified.')

**Comment by feuler** [comment]
> Would it be easily possible to enable using https://huggingface.co/vidore/colqwen2-v0.1 with byaldi?
> 
> Currently `RAGMultiModalModel.from_pretrained("vidore/colqwen2-v0.1")` leads to
> 
> > ValueError('This pre-release version of Byaldi only supports ColPali for now. Incorrect model name specified.')

I guess in the meanwhile you could change the file https://github.com/AnswerDotAI/byaldi/blob/main/byaldi/colpali.py 
to support it. (lines 10, 67, 81+82)
See definitions: https://huggingface.co/vidore/colqwen2-v0.1
Some things are different. e.g.:
- from colpali_engine.models import ColQwen2, ColQwen2Processor
- model = ColQwen2.from_pretrained...
- processor = ColQwen2Processor.from_pretrained...

**Comment by jpetrantoni** [comment]
@feuler Thoughts on #29 ? Probably could check for correct model, init model, and init processor a little cleaner but didnt want to change too much.

**Comment by feuler** [comment]
> @feuler Thoughts on #29 ? Probably could check for correct model, init model, and init processor a little cleaner but didnt want to change too much.

Thank you very much ! Just tested it, and it seems to work fine.

**Comment by bclavie** [comment]
Great contributions by @jpetrantoni who got it to work before I even recovered! Will ship a release very soon.
