### ISSUE TITLE
Where should i put the models?

### ISSUE THREAD

**Issue by metantonio** [AnswerDotAI/byaldi#39]
I downloaded the models manually, is byaldi does automatically is not working in my case (guess that I don't know where to put the hugging face token).

So, where should I put the models?

Thanks

**Comment by bclavie** [comment]
> So, where should I put the models?

You should be able to pass the model path to byaldi like you would for any other kind of model. The model loading logic is all handed off to `colpali-engine`, which itself hands it off to HF `transformers`. 

As to where to put the token, the best practice recommended by HF is to store it as an environment variable called `HF_TOKEN`. If this isn't properly being fetched, please do feel free to report back, as it'd be a weird bug in how the library interacts with its dependencies!
