### ISSUE TITLE
How to make from_index() faster?

### ISSUE THREAD

**Issue by kubni** [AnswerDotAI/byaldi#41]
Hello.
I have the index saved to disk (4 json.gz files, and one embeddings_0.pt file).
`from_index()` takes anywhere between 15-30 seconds, which seems like a long time, given that the index is saved to disk.

I have verbosity set to 1, and it seems to me that the `Loading checkpoint shards` part is taking majority of that time.
What can be done to make it faster?

**Comment by bclavie** [comment]
Hey, thank you for flagging!

`Loading checkpoint shards` is not actually part of the indexing, but it's the usual huggingface `transformers` message while it's loading the model (so you can properly embed the queries).

Loading big models' shards is often quite slow. If this is problematic, you could try looking at how people have tried to optimise it in the past (e.g. https://github.com/huggingface/safetensors/issues/333)
