### ISSUE TITLE
integrations folder not installed

### ISSUE THREAD

**Issue by hubkrieb** [AnswerDotAI/byaldi#42]
When installing the package with ```pip install byaldi``` the integrations folder is not installed.
The folder is indeed missing in the .tar.gz and .whl files on [PyPi](https://pypi.org/project/Byaldi/#files)

**Comment by bclavie** [comment]
Hey, thanks for raising. I'll look into this next week when I'm back from ([medical]) time off!

**Comment by bclavie** [comment]
Fixed in 0.0.7!
