### ISSUE TITLE
Any plans to support ColQwen2 + Similarity Maps?

### ISSUE THREAD

**Issue by asmith26** [AnswerDotAI/byaldi#47]
Hi there,

I recently came across this tweet regarding ColQwen2 + Similarity Maps from @tonywu71https://x.com/tonywu_71/status/1846870432831402315

Just wondering if there are plans to support these?

Many thanks for any help, and this amazing work/lib!

**Comment by enzokro** [comment]
Confirmed for others, I updated the colpali-engine and colqwen is off to the races!

**Comment by bclavie** [comment]
ColQwen2 is indeed easy to support and is something we absolutely want in byaldi (and we do have now, I just forgot to reply to the issue...)

As for the similarity maps, I think that's something we don't necessarily want to support to keep the core APIs lightweights, but a contribution on how to use the byaldi API to get embeddings for it and generate the same maps would be a great cookbook to add to our examples :)

Thanks @tonywu71 for answering the issue in the first place 😄
