### ISSUE TITLE
Integration Failure

### ISSUE THREAD

**Issue by DebopamParam** [AnswerDotAI/byaldi#56]
Hey @bclavie I tried to add method save_pretrained() to RAGMultiModalModel but Integration test failed thrice. I am not able to figure it out after reading the exception message, I see the ByaldiLangChainRetriever is used in RAGMultiModelModel class - please have a look at it.

```python

#Inside RAGMultiModalModel class
def save_pretrained(self, directory_path: str) -> None:
    """
    Save the model and processor to a specified directory.

    Parameters:
        directory_path (str): The path to the directory where the model and processor should be saved.

    Returns:
        None

    This function saves both the model and processor components of the current instance
    to the specified directory, allowing the model to be reloaded later from this checkpoint.
    However, for complete local setup follow this - https://github.com/illuin-tech/colpali/issues/129

    Raises:
        FileNotFoundError: If the specified directory does not exist.
        PermissionError: If there are insufficient permissions to write to the directory.
        Exception: For any other unexpected errors during the save process.
    """
    try:
        # Attempt to save the model and processor
        self.model.model.save_pretrained(directory_path)
        self.model.processor.save_pretrained(directory_path)
        
    except FileNotFoundError as fnf_error:
        raise FileNotFoundError(f"The specified directory '{directory_path}' does not exist.") from fnf_error
    except PermissionError as perm_error:
        raise PermissionError(f"Insufficient permissions to write to '{directory_path}'.") from perm_error
    except Exception as e:
        raise Exception(f"An unexpected error occurred while saving: {e}") from e
```

Exception Message:
![image](https://github.com/user-attachments/assets/83a5838d-e060-433c-bccb-212885a5285c)

I also have small request. I want to learn and contribute more to this amazing project & also the others that you are a part of. I will make a video on a project that I made recently - A complete local Multimodal RAG for large volume of PDFs using Byaldi & Pixtral. If you could take out 30mins of your time anyday if you want to be my guest, I would feel really honored. Here are some of my [works](https://www.youtube.com/shorts/0ZR0IWiZJQE) and [videos](https://www.youtube.com/@DCparam/videos). I have sent you connection request on LinkedIn, you can also find my social links [here](https://linktr.ee/DebopamChowdhury) sir when you scroll down. Thank you, Benjamin.

**Comment by bclavie** [comment]
Hey!

Apologies, I've got very little spare time at the moment, so I'm not currently on socials very much (especially LinkedIn) or able to check out much! I do appreciate your commits greatly.

The errors are very minor here. In fact, F401 we should just ignore entirely, and the I001 is just isort not having been ran with `ruff`. Neither of those are things that I feel strongly about, and there doesn't seen to be any major errors, so do feel free to resubmit your PR!

**Comment by DebopamParam** [comment]
No worries. Thanks man.
I have opened a new PR :D
